Improve benchmark firmware organization
CharlyCst/miralis pull request #139
Opened 2024-08-13 10:36 UTC by NoeTerrier

Add a way to parametrize benchmark. The helpers for reading environment values have been factorized into a crate and can be now be called inside firmware.

Move benchmark firmware into firmware/benchmark/

Add write_csr benchmark into the CI.

2024-08-13 10:37 UTC, NoeTerrier commented on config/qemu-virt-benchmark.toml
> +nb_iter=10
```suggestion
nb_iter = 10
```

2024-08-13 14:16 UTC, CharlyCst requested changes
I have just some small remarks but looks good otherwise, thanks!

2024-08-13 14:16 UTC, CharlyCst commented on firmware/benchmark/csr_write/main.rs
> +    let iterations = parse_usize_or(option_env!("MIRALIS_BENCHMARK_NB_ITER"), 1);
We will need to read this environment variable from multiple firmware images in the future, so we should probably factor it out in a single place. The `abi` crate is made for that, it defines functions for the firmware to interact with Miralis and other common utilities (such as initializing the stack, etc...)

2024-08-13 14:16 UTC, CharlyCst commented on runner/src/artifacts.rs
> +fn find_artifact(firmware_path: &PathBuf, name: &str) -> Option<Artifact> {
Let's call it `find_artifact_source`. There are multiple kinds of artifacts (sources or binaries), here we only look for sources that we can compile.

2024-08-18 16:41 UTC, CharlyCst approved these changes
Thanks for the changes, look all good :)

2024-08-18 16:49 UTC, merged